[pytest]
# https://github.com/scrapinghub/dateparser/issues/1013
filterwarnings = 
    ignore:The localize method is no longer necessary, as this time zone supports the fold attribute
    ignore:Parsing dates involving a day of month without a year specified:DeprecationWarning:dateparser.utils.strptime
    ignore::pod2gen.NotSupportedByItunesWarning
    ignore:^Size is set to 0\.:UserWarning
